[package]
name = "fn_activator"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
hidapi = { version = "2.6.1", default-features = false, features = ["linux-native"]}
